### ISSUE TITLE
Remove Books from Database?

### ISSUE THREAD

**Issue by ranmaru90** [janeczku/calibre-web#119]
Is there a way to remove books from the database?

**Comment by OzzieIsaacs** [comment]
Up to now, its not possible to remove books from the database via calibre-web, but I was also thinking of implementing ist

**Comment by ranmaru90** [comment]
Then what is the proper way of removing the books so that they are not displayed on the page anymore? I tried removing them via calibre itself, but the books are still shown, and can still be read.

**Comment by OzzieIsaacs** [comment]
This should work, i've got to check. Maybe it's related to #42.

**Comment by OzzieIsaacs** [comment]
I've checked it. It works for me. If you delete the file in calibre it disappers in calibre-web.

Just to make sure, after you deleted the file in calibre, you reloaded the webpage of calibre-web?
Does the book disapear if you stop and restart calibre-web?

**Comment by ranmaru90** [comment]
Ahh yes, the books do disappear when I restart calibre-web. Thanks!

**Comment by OzzieIsaacs** [comment]
To find out the reason, could you please tell me which linux you are using and which filesystem type (ext4,ext3, ...) you are using? 
Which python version are you using? 
Which version of calibre do you have installed?

**Comment by ranmaru90** [comment]
Raspbian Jessie
ext4
Python 2.7.9
calibre 2.75.1

**Comment by OzzieIsaacs** [comment]
Could you please install the latest commit, go to the about section and could you please tell me the version of the pysqlite driver and the sqlite version.
Thanks in advance

**Comment by ranmaru90** [comment]
SQlite	v3.16.2
Pysqlite	v2.6.0

**Comment by OzzieIsaacs** [comment]
I did some checks, everything works fine for me, even with the library versions you use. I added a button to reload the calibre database in the admin config section, could you please try if this solves the problem. Further I added the ability to log the database requests. Could you please set the debug level to DEBUG display a book, than delete it in calibre, reload the page in calibre-web and than paste the löffele, or send it to me via email. I try to find out what's the reason than

**Comment by ranmaru90** [comment]
After updating to the latest, I got 

The 192.168.0.3 page isn’t working
192.168.0.3 redirected you too many times.
Try clearing your cookies.
ERR_TOO_MANY_REDIRECTS

**Comment by OzzieIsaacs** [comment]
Thanks for the data I'll take a look at it and give you feedback

**Comment by bluebird11** [comment]
+1 for implementing "remove book from library and delete from disk".

Thanks for the otherwise perfect piece of software!

**Comment by OzzieIsaacs** [comment]
Thanks for the data you send me. Meanwhile I had a chance to analysze it. I didn't find any hint whats going wrong on your system. For me everything works.

**Comment by OzzieIsaacs** [comment]
I added a button for deleting books from the database. All currently existing users are not allowed to delete books. The admin user can activate it in the user administration section.

**Comment by bluebird11** [comment]
Thanks a lot!

However, I don't see the delete button here. I checked "Allow Delete books" for the user and submitted and received a confirmation "User '***' updated". I tried logging out and back in.

Am I missing something?

**Comment by OzzieIsaacs** [comment]
The button is not on the normal "view a book" page, it is on the "edit book" page. (At least for me, if it's not like this, please comment again)

**Comment by bluebird11** [comment]
Thanks a lot for the tip! The button is there. However, this is what I get when I click it:

```
Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```

**Comment by OzzieIsaacs** [comment]
Could you please paste the content of the calibre-web.log file related to the error

**Comment by bluebird11** [comment]
I guess it's this one:
`[2017-04-14 21:05:28,618] {/usr/local/lib/python2.7/dist-packages/flask/app.py:1560} ERROR - Exception on /delete/210/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/home/pi/calibre-web/cps/web.py", line 1294, in delete_book
    modify_database_object([u''], book.languages, db.Languages, db.session, 'languages')
  File "/home/pi/calibre-web/cps/web.py", line 500, in modify_database_object
    type_elements=c_elements.name
AttributeError: 'Languages' object has no attribute 'name'`

**Comment by OzzieIsaacs** [comment]
@bluebird11 
Thanks for the log. Fixed it. Should work now, please try again with newest version

**Comment by bluebird11** [comment]
Unfortunately, I'm still getting the same error even after the update :(

I can send you the log when I get home.

**Comment by OzzieIsaacs** [comment]
Yes please send me the logbook, I'll check it than

**Comment by bluebird11** [comment]
Here's the new log:

`
[2017-04-15 17:57:02,278] {/usr/local/lib/python2.7/dist-packages/flask/app.py:1560} ERROR - Exception on /delete/210/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/home/pi/calibre-web/cps/web.py", line 1315, in delete_book
    del_cc = getattr(book, cc_string)[0]
IndexError: list index out of range
`

**Comment by OzzieIsaacs** [comment]
It was diffrent from the first error. It was related to custom columns. 
I hope now I got all possiblities.
Please try again.

**Comment by bluebird11** [comment]
Now it works! Thanks a lot! That's a really great piece of software!
