### ISSUE TITLE
Controlling Calibre-Web database writes

### ISSUE THREAD

**Issue by haertig** [janeczku/calibre-web#1982]
**Is your feature request related to a problem? Please describe.**
I would like to run Calibre-Web with a read-only database.  I do not add/delete/update anything in Calibre-Web, I do that in Calibre.  I used to be able to run Calibre-Web against a read-only database in prior versions.  But apparently this does not work any more.

**Describe the solution you'd like**
Add a startup flag to Calibre-Web instructing it to not attempt any writes to the database, or to silently fail without errors, warnings or crashes should a database write fail.

**Additional context**
For years I have run Calibre on computer A and rsynced it's database to computer B where Calibre-Web is running in a Docker container.  The computer B copy of the database was mounted read-only into the Docker container.  After the rsync, I restarted Calibre-Web's Docker container to pick up changes in the database.  Calibre-Web was configured so that users could not do additions/deletions/updates so Calibre-Web never ran into any write failures (apparently because it never attempted to write), and all worked well.

When updating Calibre-Web Docker image today (which moves Calibre-Web from 0.6.8 to 0.6.11), suddenly it will not work with a read-only database.  It is attempting writes for unknown reasons.  The only thing I did was click on the navigation button "Series", which caused Calibre-Web to crash.  The same thing happens if I click on "Categories".  But not if I click on "Authors".  The displayed error mentions database writes:

_(sqlite3.OperationalError) attempt to write a readonly database
[SQL: UPDATE authors SET name=? WHERE authors.id = ?]_

I do not understand why Calibre-Web needs to write to the database at this time.  But that's not my business/concern.  Is it possible to configure Calibre-Web to not treat these write errors as fatal?  Or could that functionality from prior versions be restored or enhanced by adding a new startup flag?

**Describe alternatives you've considered**
I want to use Calibre-Web to browse and download books only.  Nothing else.  It should be able to accomplish that without requiring database writes.  It performed this way in the past.  There are workarounds for my current scenario: (1) Stop Calibre-Web, (2) rsync, (3) restart Calibre-Web with readwrite permissions, (4) doesn't matter if Calibre-Web writes to the database since it will be overwritten on the next rsync.  However, I was planning in the future to run both Calibre and Calibre-Web on the same computer, against the same database - but restricting Calibre-Webs write operations.  This future plan no longer seems possible with the unexpected writes that Calibre-Web now attempts and treats as fatal.  I do not want Calibre-Web to write to the database because: (1) Potential for problems if Calibre-Webs understanding of database functionality gets out of sync with Calibres use of the database (different developers, so this is a real possibility), and (2) The potential for both Calibre-Web and Calibre to attempt writing to the database at the same time and causing corruption (Calibre warns strongly against this very thing - multiple users writing to a shared or networked database).

**Comment by OzzieIsaacs** [comment]
It should be fixed in the newest version

**Comment by OzzieIsaacs** [comment]
Duplicate of #1963

**Comment by gitterspec** [comment]
I think this should be re-opened as I would really welcome a read-only option.

When using linuxserver/calibre together with linuxserver/calibre-web, I am still getting issues where the database becomes locked by calibre-web and never gets unlocked.

I, like many others, use calibre-web to serve books, not to edit the library.
