### ISSUE TITLE
Some epub files do not import covers correctly on Calibre-Web, which affects Kobo Sync

### ISSUE THREAD

**Issue by ryanmichaelmcclure** [janeczku/calibre-web#2294]
**Describe the bug/problem**

When uploading some epub files to Calibre-Web, the cover says "Cover Not Available". All epubs that have this bug, even if a cover is manually uploaded, when synced with Kobo Sync do not render covers on Kobo devices. When these epubs are synced manually or opened in Calibre (desktop application), the cover renders fine.

**To Reproduce**
1. Upload certain epub files 
2. Upon upload, cover says "Cover Is Not Available" [https://imgur.com/p3WnZTj.png]
3. Even if cover is manually uploaded, when synced with Kobo device, cover does not appear.
4. For a sanity check, the same epub file in Calibre (desktop) renders the cover fine [https://imgur.com/r6kuLeT.png]
5. When the file is manually synced to Kobo device, file renders fine

**Logfile**
[2022-01-29 00:15:22,604] DEBUG {cps.updater:332} Stable version: {'version': '0.6.16'}
[2022-01-29 00:15:43,180] DEBUG {cps.uploader:313} Temporary file: /tmp/calibre_web/03053ffc045564439ff7f2cabb3b58c5
[2022-01-29 00:15:43,602] DEBUG {cps.helper:363} Moving title: /tmp/calibre_web/03053ffc045564439ff7f2cabb3b58c5 to /books/Tappei Nagatsuki and Shinichirou Otsuka/Re_ZERO -Starting Life in Another World- Ex, Vol. 3_ The Love Ballad of the Sword Devil (171)/Re_ZERO -Starting Life in Another World- Ex, Vol. 3_ The Love Ballad of the Sword Devil - Tappei Nagatsuki and Shinichirou Otsuka
[2022-01-29 00:15:43,885] DEBUG {cps.services.worker:88} Add Task for user: ryanmcclure - Upload File <a href="/book/171">Re:ZERO -Starting Life in Another World- Ex, Vol. 3: The Love Ballad of the Sword Devil</a> uploaded

(((Yes, I know that there's no relevant info, but that's literally all I see when uploading an epub and receive this bug.)))

**Expected behavior**
The epub file correctly extracts the cover file.

**Screenshots**
See above

**Environment (please complete the following information):**
 - OS: Linux
 - Python version: In docker so not sure
 - Calibre-Web version: 0.6.16	
 - Docker container: LinuxServer
 - Special Hardware: Synology DS418Play
 - Browser: Chrome 97.0.4692.99

**Additional context**
Add any other context about the problem here. [e.g. access via reverse proxy, database background sync, special database location]

This bug occurs when accessing via reverse proxy or local IP address

**Comment by OzzieIsaacs** [comment]
There a several ways on how the cover is detected in a epub file. Your file seems to use a method which is currently not supported by calibre-web. To find this problem I need the problematic epub file. Please send it to me via private email (on my github profile page). Thank you

**Comment by ryanmichaelmcclure** [comment]
Sounds good. I sent you some epubs. If you need more, I can give more as well

**Comment by OzzieIsaacs** [comment]
In the newest nightly Version the bug is fixed

**Comment by ryanmichaelmcclure** [comment]
The files import perfectly now. Thanks a ton! Appreciate it.

I've noticed that when using Kobo Sync, the artwork still does not render on the device. When side-loading the epub to the device, the artwork loads fine. I'm guessing something in the Kobo Sync function for Calibre-Web isn't sending the artwork? Should I make this a separate issue?
