### ISSUE TITLE
caliBlur!

### ISSUE THREAD

**Issue by leram84** [janeczku/calibre-web#454]
Soooo... i've been crazy busy [since we last spoke](https://github.com/janeczku/calibre-web/issues/170) and i've learned some shit :) My goal atm is to build a consistent ui across all user facing apps in my [organizr](https://github.com/causefx/Organizr) install. Since plex is the biggest part of that, is closed source, and i actually like the design the most anyway, ive decided to make everything fit with it. To that end, I started a repo called [layer#Cake](https://github.com/leram84/layer.Cake) to build a css layer on top of existing self hosted apps like organizr, ombi, and now calibre-web, and i've built my own themes (blur) with the plex design language as a guide, into each. 

layercake can be installed on the webserver which means you don't have to worry about messing w source or breaking updates, and since its all hosted on git, updates are automatic (using rawgit cdn network to push the .css). That being said, there are some definite advantages to building layercake directly into these apps (as we have done with organizr and ombi) so please let me know if that has any appeal to you. Anyway, I was kind of hoping to have this mostly finished before posting here, but I'm hitting a couple forks in the road, and your willingness to add a couple things for me will change the way i finish this theme. (If it's not too much trouble to attach a class to `<body>` for each url dir is the most important for example). 

Anyway, still a wip, and mobile doesn't work at all yet, but the desktop layout is 90% finished. You can check it out by adding this to your nginx location block:

```
    proxy_set_header Accept-Encoding "";
    sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://rawgit.com/leram84/layer.Cake/dev/CSS/caliBlur-Demo.css"> </head>';
    sub_filter_once on;
```
Lemme know what you think, and like i said, if you're willing to add a few (very small) adjustments for this, i can make it even better! Cheers!

SS:
![caliblur1](https://user-images.githubusercontent.com/21117493/36045515-fbe75590-0da3-11e8-89d8-f405246db043.png)
![caliblur2](https://user-images.githubusercontent.com/21117493/36045537-02869ab4-0da4-11e8-9f01-800a3e6da8e0.png)

**Comment by tomandocubatas** [comment]
I like it!!!

**Comment by leram84** [comment]
THANKS! I just realized i goofed big time though. I had built all that ^ using an apparently outdated version :/ soooooo most of that second ss doesn't actually work anymore since that whole thing is now a very differently laid out popup. I'm working on redoing it all, but will probably take an extra week or so.

**Comment by xFilosofx** [comment]
It's amazing dud. I really wont to deploy this theme on my instanse.

**Comment by OzzieIsaacs** [comment]
Looks awesome from the screenshots. Definitly worth the time

**Comment by leram84** [comment]
Thanks guys! @OzzieIsaacs does that mean you want to integrate this? Again, i won't be offended if its outside the scope, and i can still make it work as a completely external addon, I just need to know a few things before i finish. Especially if you're willing to make a few changes. I have like a 5-6 item wish list of little things that would help. For example, one thing that's bugging me is that the new popup style details page has a new set of download buttons. From what i can tell, if u have 1 format available for dl, you get 1 button for that item. If you have 2 formats you get 2 seperate buttons... but if you have 3 or more they all get pushed to a drop down list.... however the "read in browser" button is always in a drop down... even if its just 1 item. Thats actually fine since i can always take something out of a drop down, but the dl button changing from 1 button to 2 buttons, to a drop down, makes it very difficult to style... would prefer just 1 drop down no matter how many items. (thats the biggest *change*). Other issues won't change anything for the existing theme. (things like needing a class applied to `<body>` depending on what page you are on)

lemme know what you guys think and ill proceed accordingly :)

**Comment by andy29485** [comment]
@leram84 For "read in browser" button, in the comic branch, I added a small fix so that it only became a drop down when there was more than one format. Not sure how that impacts your CSS change (which looks nice by the way).

**Comment by leram84** [comment]
the drop down is actually preferred. I would rather have it even if there is only 1 item (like the read in browser button). The reason is that im forced to use fixed/absolute positioning to get those buttons up to that top row (you can see them all lined up on the top right in that second SS ^) The problem is that top bar is incredibly complicated. I have to use some overly hacky methods to make everything line up to the right, even though ppl will have a completely different set of options enabled. So if for example i set a the position of the dl button to be 60px down and 120px right, then place the next button 180px to the right so its next to the dl button... but then all of a sudden there are 2 dl buttons where there was only space allotted for 1 it messes everything up. The solution i would probably work on in that case would be to pull the button from the top bar and do something different so it works for all the various layout possibilities... it just won't look as good imo.

Like i said there are a few issues like this, it might be easier to talk in chat if u guys are on discord or something. (actually if any of you are interested, we have a very very active community on the organizr discord. and a bunch of us are currently working on book projects. Feel free to swing by if you want https://discord.gg/rZXH7hu )

ohhh and btw... comics branch?!! is that what it sounds like? u guys building a comics version of this? I've gotten a few requests to "blur" ubooquity as well since i started this and  i said i would take a look (i dont actually do anything w comics atm), But would def be interested to look at the calibre-web take on comics (if im understanding you correctly)

**Comment by OzzieIsaacs** [comment]
The comics branch is a changed version of the comic reader with a slightly diffrent ui than now, and downloading the paging on request and no longer everything on the beginning, but I have a lot of other projects currently going on, so no progress on this topic for a long time.
I might have to time to take a look in the stuff you did and in (theming in general ) this weekend, and than I can decide how to merge/integrate/deal with it.

**Comment by adocampo** [comment]
Impressive that Plex theme! I'll test it as soon as I can! 👍

**Comment by leram84** [comment]
Ok, so i got this thing pretty much as far as i can take it on my own (thats a lie... i could actually finish it without any changes on your end, i would just have to make some unfortunate compromises). So figured i might as well start outlining some of the more important adjustments i could use:

1) Classes - The hardest part of this, obviously, is the selector soup im working w lol. Adding a class to `<body>` for the page you are on will help tremendously and take care of 95% of the current bugs. So that means if you are on the "series" page, add `series` class to `body`, if you're on the first page (where u go when u click the calibre logo) add `recently-added` class to the `body`. If you are on a double url like "sort by title (Descending)" add `books-z-a` (or something like that) to the `body`. I could also use a class for the user-level of the current user (guest/user/admin). The other part where this really matters is the actual reader. I really need the `reader` class added to all `body` lines in the page (so it has to be in the iframe of the book itself as well.

2) Download Button - Right now its set to if > 2 move to dropdown. I need if > 1, move to dropdown.

3) Glyphicon-Halflings - I could use an update on this. Lots of icons i would like to use are not available.

4) Active Class for sidebar items - Its a small one, but its the only glaring difference from plex so its triggering my ocd lol. If you can add an `.active` class to the sidebar items when active i can then make the current tab turn yellow in the sidebar.

The other thing i wanted to talk to you about was the reader itself. My goal w the class request above was to allow me to disable all my css on that page (cause its currently bringing in the blur bg lol), but i do still think CW proper could use a "dark-mode". Would this be a challenging thing to to add on your end? the css is pretty straight forward (just colors and backgrounds), but it would need a way for the user to select one.

Lemme know what you think. The demo is caught up to the current version so its back to 90% lol, but im working on mobile separately so it will break at >768px. If you want to see the direction im going in mobile you can replace the url w `<link rel="stylesheet" type="text/css" href="https://rawgit.com/leram84/layer.Cake/dev/CSS/caliBlur-Mobile.css">` But its still early days for that.

**Comment by GBochicchio** [comment]
It looks fantastic! Good job @leram84 ! I am waiting for updates!

**Comment by teflontoni** [comment]
I applaud to the effort, and it's a fresh look, but for me it looks too distracting.
I like the actual theme as the book covers make it 'pop' and they don't have to compete against other bright colors. So if it's merged into calibre please make it optional for the more conversative folks ;-).

**Comment by leram84** [comment]
HA! yeah dude, no worries there. I was never trying to replace the default ui. This makes more sense if you're running organizr since im working on pulling all the user facing apps into a unified design. Currently, the best apps (from our perspective) and the ones i have included (or will include) in layer#Cake are:

Movies/TV: Plex
Music: Airsonic
ebooks: Calibre-Web
Comics: used to be ubooquity, but another guy on our team is working on a few PR's to make the calibre-web comics branch better (so i dont have to do all this front end shit on ubooquity lol)
abooks: Currently booksonic, but since the dev has no plans to support ios and im starting to actually believe people are starting to care about abooks again, im not gonna bother w that for now. Im holding out for embook (plugin for emby) or Plex to actually make abooks functional.
User Manager: Ombi
And organizr to wrap it all up.
(oh, and i MIGHT work on striping down lazylibrarian to make a user facing version like a poor mans ombi, but thats another one that im hoping gets taken out of my hands if someone gets around to forking lidarr for it instead of headphones... Iv even registered r/binocularr for whoever wants to jump on this :) )

But with all of these, layer#Cake is built on top of the existing ui so it will always be optional.

**Comment by leram84** [comment]
Emby colors for example:
![emby colors](https://user-images.githubusercontent.com/21117493/36860184-906018ce-1d4e-11e8-84eb-a763577245ea.PNG)

**Comment by andy29485** [comment]
So I've really liked the new interface as a whole, but I have complaint about the book details screen.

| Description | Image |
| ------------ | ---------------- |
| What it looks like in the `master` branch. | ![master](https://puu.sh/zF1ys/0e6aceb935.png) |
| What it looks like in the `comic_server` branch. | ![comics](https://puu.sh/zF1Cn/7843f1535f.png) |
| What I would ideally want it to look like. | ![ideal](https://puu.sh/zF1CW/f221326f0b.png) |


1. From what I understand the comic_server branch looks like that because you don't yet seem to support non-drop down for the read button (only when one book).
  - It really gets annoying to have to click 2 buttons when 1 is be enough - in fact, why does that menu even exist, there's only one option.
  - This (like the download button) should *only* be a menu when there's more than one option (better design - faster and more intuitive for the user and consistent with the other buttons).
2. The whole thing is all over the place. I understand that that's in part due to the html not having the 3 buttons in the same group, but that can be fixed with a simple pull request (maybe even have the css code be part of this repo as opposed to being an outside thing).
3. Buttons don't have text. I can understand for mobile, where there's not much room, but this is the desktop demo (not using the mobile css).
  - The `READ` button looks almost the same as the `LOGOUT` button (even in a similar position... but slanted and no text).

**Comment by leram84** [comment]
Cool! Thanks for checking it out.

Ok, so first of all, yes, everything you've outlined are known issues and can all be addressed with those 4 issues i've outlined above. Well, thats probably the easiest way to address them all (least amount of work for you guys) but certainly there are several ways to make it all much better, i just didn't know how much support i could expect from you guys for this since this whole project is kind of out there lol. And i would need those PR's to come from you guys just to be clear... I've literally only learned html/css a few months ago and not really capable of making any of these adjustments as a PR. 

But to your points:
1) Yes, i only just saw the comics branch once @tailchakra setup his site to start working on his PR, and that was the first thing i noticed. It should be easy enough to make that button work though, and i would agree with you about all of those buttons. Right now, the download button shows 1 button (if theres just 1) 2 buttons if theres only 2, and a dropdown for 3+. and then read in browser shows a dropdown regardless of the number (even 0), unless its comics branch. Obviously 1 scheme for all these would be preferred. But the only issue with having a button instead of a dropdown for single items, is that you will then end up with an empty space when there is no option available... which brings me to 2

2) All over the place is an understatement lol. If you look at that top row, its pooling buttons from the dl/read section at the top of the book details page, the "read/unread" check box from the middle, and the edit metadata/playlist buttons from the bottom. So i had to use absolute/fixed positioning to make it all work, and then lay it out in a way that wouldn't break depending on all the different configurations each user might have... like i said, i can make it "work" with those 4 things i requested above, but obviously there are way better ways to handle this and do even more depending on how far you guys are willing to go with this. 

3) ok, a bunch of things. First of all, yeah, the no buttons thing was intentional. Im not sure if u use plex. but im using their design language for this. I didn't want to over complicate my requests, but after all this stuff got straightened out, was going to make one last request to add tooltips to a bunch of items. (and i wont even know everywhere i need them until the whole thing is complete and all design choices are made). But this is the ux im going for:
![screenshot 2018-03-11 at 1 25 02 pm](https://user-images.githubusercontent.com/21117493/37256373-2a09831e-2530-11e8-9617-2932b18f783e.png)
 I personally like the clean use of icons only (with tooltips for more info) cause after you use it once, you will know what does what and this just looks better imo.

3a) For the read icon see request # 3 ^ above lol... i need halflings updated ;)

**Comment by leram84** [comment]
ohh, and i should point out theres one other issue thats driving me crazy because i dont really have a good solution. While im making the book details page look like a whole page, its really just a popup, the problem is that it makes the user think they can use the browser back button, but obviously that wont bring them back to the list of books because they are technically still on that page. I'm not sure what (if anything) can be done about this, so just wanted to point it out in case someone had an idea

**Comment by andy29485** [comment]
> While im making the book details page look like a whole page, its really just a popup, the problem is that it makes the user think they can use the browser back button, but obviously that wont bring them back to the list of books because they are technically still on that page. I'm not sure what (if anything) can be done about this, so just wanted to point it out in case someone had an idea

This can be easily changed "go to page" instead of "pop up" by changing a few lines (although what I'm suggesting is a minimal patch, more code can be removed). The html code in question is `data-toggle="modal" data-target="#bookDetailsModal" data-remote="false"` which is located in a few files:

```bash
$ grep 'data-toggle="modal" data-target="#bookDetailsModal" data-remote="false"' -r .
./cps/templates/search.html:        <a href="{{ url_for('show_book', book_id=entry.id) }}" data-toggle="modal" data-target="#bookDetailsModal" data-remote="false">
./cps/templates/shelf.html:         <a href="{{ url_for('show_book', book_id=entry.id) }}" data-toggle="modal" data-target="#bookDetailsModal" data-remote="false">
./cps/templates/discover.html:      <a href="{{ url_for('show_book', book_id=entry.id) }}" data-toggle="modal" data-target="#bookDetailsModal" data-remote="false">
./cps/templates/index.html:         <a href="{{ url_for('show_book', book_id=entry.id) }}" data-toggle="modal" data-target="#bookDetailsModal" data-remote="false">
./cps/templates/index.html:         <a href="{{ url_for('show_book', book_id=entry.id) }}" data-toggle="modal" data-target="#bookDetailsModal" data-remote="false">
```

This can be quickly fixed with a single command:
```bash
sed -i -e 's/ data-toggle="modal" data-target="#bookDetailsModal" data-remote="false"//' cps/templates/discover.html cps/templates/index.html cps/templates/shelf.html cps/templates
```

**Comment by OzzieIsaacs** [comment]
Hi, I integrated the css (with option to enable it). I named it "caliBlur! Dark Theme". 
Feel free to create a PR to change the name  (cps/templates/user_edit.html line 38)
I marked it as Beta as there are some issues.
Regarding the modal view mentioned from @andy29485. This was changed by @jkrehm a few month ago, to make "mass" editing books more comfortable (e.g. change all books from a search result).

**Comment by leram84** [comment]
hey ozzie! Are you saying you made all the adjustments i outlined in https://github.com/janeczku/calibre-web/issues/454#issuecomment-366811910 ? or just that you integrated the css as is, into CW. If its the latter, do you think you can manage those requests? Also, if you are going the direct integration route with this, can you make it work without rawgit? I'm using those links because github doesn't pass the mime type, so if i use the actual github url as a subfilter, the browser reads it as .txt. But if you are integrating this directly, there are a bunch of ways to easily parse the mime type so i can just use the actual github links without passing them through rawgit servers first. 

Anyway, thats all cosmetic until i actually know how im going to finish this thing... ergo https://github.com/janeczku/calibre-web/issues/454#issuecomment-366811910 lol

**Comment by OzzieIsaacs** [comment]
I only integrated the css as is, it’s switchable on and of per user.
I can integrate it in the repro. 
I‘ll have to take a look at the changes you requested.

**Comment by OzzieIsaacs** [comment]
The download button: Having single buttons was requested in #40 (for good reasons, I think) so I think it would not be a good idea to revert the change. Sorry

**Comment by leram84** [comment]
it seems the issue in #40 was the drop down's position on the kindle... would those people still not have the same problem if they have >2 formats for a book (which would still move everything to a dropdown)? It's up to you, but if there is still a problem there, im happy to fix that so that it works with +2 formats as well on your stock theme. But the issue im having is that currently it shows 1 button, 2 buttons, or a drop down for 3+... would you be willing to make it just either 1 button, or a dropdown? The only change there would mean that kindle users w exactly 2 formats would now get a dropdown instead of 2 buttons, but nothing else would change (and like i said, i can fix the css on that dropdown so it doesn't cause issues on kindle... which it seems would be necessary for kindle users w 3 formats anyway right?)

... am i getting this right?

**Comment by simkin** [comment]
Very nice skin, excellent work and thanks for sharing

**Comment by h3xcmd** [comment]
Awesome look. We have the same taste and design on how we want our library servers to look and feel. It's really sad right now that Plex is more focused on updating it's app and music experience than listening to it's users that have this interest. I really wish Plex would intergrat ebooks. 

I was looking around google and your like the only person in the world that has come so close to this. 

I run an unraid server and I discovered the amazing-ness of docker containers for Plex and plex themed ubooquity verses the traditional VM's.

Ubooquity is alright, and the Plex theme makes it much better and mobile friendly however it's not the same. Missing cool stuff that Calibre offers and does not have the drive that Plex offers.  

Keep up great work your doing, it's bleeping awesome.

**Comment by leram84** [comment]
thank you! its coming along, but damn is this stuff time consuming! lol This theme is ~90% completed, but I actually got distracted w other projects for a while, but i was still waiting to hear from someone if they wanted to tackle some of the requests i made above ^. They are relatively small adjustments, but outside my skill set. If not, ill eventually make this all work without it, but ill need to study jquerry a lot more to make the adjustments i need, and itl probably be at least another 6ish months till i have that kind of time.

**Comment by OzzieIsaacs** [comment]
Okay, I modified things like requested on Feb 2nd (sorry for the long delay)
1:) Did it, not 100% sure if I did it right
2:) Done
3:) Please tell me, which you need, or please add it via PR yourself. I'll merge it then.
4.) Integrated it, but I'm not sure if it's right: What to do with the dropdown in the sidebar (per selected element?). What to do for like authors and authors list? (Currently only for authorlist active is set, which might be wrong?)

I'm going to check the book details stuff

**Comment by aroundmyroom** [comment]
nice, but the configuration part is unreadable 

![image](https://user-images.githubusercontent.com/250108/42736682-74c26036-886a-11e8-9908-936511608ab3.png)

**Comment by aroundmyroom** [comment]
![image](https://user-images.githubusercontent.com/250108/42736695-9bc1ad18-886a-11e8-9bce-3009d4b0a194.png)

**Comment by OzzieIsaacs** [comment]
It’s work in progress, be patient

**Comment by leram84** [comment]
Hey! so i've been meaning to drop an update here, but life... yada yada yada lol. I literally got some help w the jquerry stuff a couple weeks ago and started making some progress right before your update :) Your changes definitely helps, but its not all the way there, so i will still need to include some jquerry w the theme. The good news is that by including the js file i can now do a lot more than initially planned, and save you from making out of scope changes to calibre-web proper. I actually dont think i need anything else to finish from this point! There is still quite a bit of work to be done on mobile, but i think i can release the desktop version of this theme pretty soon (it will just revert to default theme on mobile for now).

**Comment by astrodad** [comment]
This is really interesting, and I am so hype for this. I sometimes just like to pop open the url in the browser and enjoy the book covers. It's sort of like going to the library or book store. The current UI is too bright, but your modifications look just right to me.

**Comment by leram84** [comment]
not even a little lol... rn the desktop version is 99% complete... just need to fake some content in the tasks page so i can skin that, but everything else is done. assuming i can get that working tomorrow, ill try to push the new version to you guys tomorrow night. It will work very well, but will just revert to default when the screen width is <768px. Since @hexeth came on board to handle the jquery, we've gone full ham on this thing and it looks/feels downright identical to plex now. But thats also why its taken so long and why mobile will likely be a while longer too.

**Comment by itsmehemant123** [comment]
Holy, this looks great! 

You mentioned at the start about being interested in integrating this theme into calibre web itself. Is that still happening?

**Comment by OzzieIsaacs** [comment]
You can activate the theme per user on the user settings page.

**Comment by leram84** [comment]
Not really... that never really worked. Its just an unfinished snapshot of the (very beta) css file from months ago. I was waiting till i finished to discuss this, but theres a couple issues with that. First of all, this thing has come a LONG way since then. This isn't really a theme anymore. I've built an entirely new ui. So if you want to incorporate this directly into cw that way, you're going to need to include some js. But the main problem (even with the old theme) is the staticness. It needs to pull the code from my repo for updates. If a new feature is added, ill need to Incorporate it,and that will have to be updated. I also dont like the per user option of enabling this. It was designed to be a complete ui globally (but that's just a personal preference)... These are the main reason's i designed this as an add-on. From my side it will be able to be installed manually (will get live updates from me, but will have to be re-installed every time cw proper sees an update), or as an nginx subfilter (preferred - it will be auto-updated on both cw's side as well as my own). The reason i'm doing it like this, and was never willing to do something like fork cw all together is because this is only one part of a larger project I'm working on. So i need to keep all the code in the layercake repo for it to all work, but It's all oss, so you guys are welcome to pull it all into cw however you like as well. 

And just to give an update on progress... obviously i did not end up releasing a "desktop only" version of this. It ended up being too much work in the wrong direction to make 2 separate versions, just so i could push something out sooner, so i gave up on that and have basically locked myself in a dark room until i finish the entire thing properly. I've learned my lesson about attempting release dates lol, but I will say I'm now well into the mobile work, and the overall project is very nearly finished (week(s) not month(s))

**Comment by itsmehemant123** [comment]
Oh, understood. Cant wait!

By the way, does the theming apply to the epub pages while reading, or is it only for the browsing view? I've always wanted a dark mode for calibre-web's epub reader, and this would be perfect.

**Comment by adocampo** [comment]
Dark mode for reading would be great, indeed!

**Comment by leram84** [comment]
It would be relatively trivial to implement. Something like this would let you configure however you want on the fly:

```
:root {
    --color-background: #474747;
    --color-title: #fff;
    --color-active: #ccc;
    --color-hover: #999;
    --color-button: #666;
    --color-divider: #fff;
    --color-shadow: hsla(0,0%,100%,.45);
    --color-text: #eee;
}
#main {
    background: var(--color-background);
}
#titlebar {
    color: var(--color-title);
}
#titlebar a:hover {
    border: 1px var(--color-hover) solid;
}
#titlebar a:active {
    color: var(--color-active);
    -moz-box-shadow: inset 0 0 6px var(--color-divider);
    -webkit-box-shadow: inset 0 0 6px var(--color-divider);
    -ms-box-shadow: inset 0 0 6px var(--color-divider);
    box-shadow: inset 0 0 6px var(--color-divider);
}
#divider {
    border-right: 1px var(--color-divider) solid;
    box-shadow: -2px 0 15px var(--color-shadow);
}
.arrow {
    color: var(--color-button);
}
.arrow:hover {
    color: var(--color-hover);
}
.arrow:active {
    color: var(--color-active);
}
[class^="calibre"] {
  color: var(--color-text)
}
```

![cw-dark-mode](https://user-images.githubusercontent.com/21117493/45576529-821d1b80-b845-11e8-825e-da201f793512.PNG)
But this should really be done on cw itself so the user can decide if they want to enable it or not. The settings menu under the "Reflow text when sidebars are open." option would be a great spot for an "enable dark mode" toggle.

**Comment by leram84** [comment]
IT'S DONE!!!! Seems my timing might be a little problematic here cause it was actually finished a few days ago, but there were some ui changes in the latest release... I'm seeing a lot of activity rn actually, so there might be issues going forward. But for right now, this is completely up to date w the current version of cw. What an adventure! :) 
https://github.com/leram84/layer.Cake/tree/master/caliBlur

**Comment by leram84** [comment]
@OzzieIsaacs had a chance to look at this? Whenever you're free id love to dm you about integration now that this is complete. Discord would probably be easiest if you're on it (I'm `leram84#8267`), otherwise i can meet you wherever you'd prefer?

**Comment by adocampo** [comment]
Just tried again caliBlur on calibre-web. So far so good (dropdows, tags, etc). Just mention some points:
 - Logon screen still have the default theme
![imagen](https://user-images.githubusercontent.com/2266612/47963442-dc0fb580-e02c-11e8-84c7-7436efa873f1.png)
 - Settings are quite difficult to read
![imagen](https://user-images.githubusercontent.com/2266612/47963439-cb5f3f80-e02c-11e8-992f-6d352cac8bd7.png)
- Book details is a mess
![imagen](https://user-images.githubusercontent.com/2266612/47963464-21cc7e00-e02d-11e8-877c-d23417006802.png)
- Read in browser still white 

I don't know if there is something wrong from my side. I'm using technosoft's docker with bodybybuddha app_repo.

**Comment by gilbN** [comment]
Are you adding it using the gui? If you are you will have to disable that. That version is very broken/alpha. Read this https://github.com/leram84/layer.Cake/blob/master/caliBlur/README.md#instalation

**Comment by adocampo** [comment]
Yes, I selected caliBlur from the GUI settings on calibre-web. So, the right way to do it is through a reverse proxy? I'm using traefik at the moment as reverse proxy... I guess I should wait until the theme can be set on calibre-web, then. (or figure out if it can be accomplished with traefik)

**Comment by hexeth** [comment]
@adocampo Unfortunately, caliblur will only ever be supported via reverse proxy

**Comment by leram84** [comment]
we should really talk about this. The language work is pretty much done too, but we need to straighten out integration. @OzzieIsaacs are you on discord? would like to get you and hex in a room for a few minutes.

**Comment by leram84** [comment]
ok, ill have the final css update in the next day or 2. The last thing i need from you @OzzieIsaacs , and i just realized we dont really need to wait for the finished blur version since It's already being updated, is to move the toggle from the user settings  to the server settings (i would suggest in the "basic UI" section, but anywhere is fine). Once thats in place ill make sure there are no issues with the final css pr and WE ARE DONE!!! ...(until the next cw update :) )

btw.. i totally forgot about that bit i did about the dark mode for the reader ^ https://github.com/janeczku/calibre-web/issues/454#issuecomment-421492247 . Do you want to add that? I wouldn't change the default colors, but if you want to put in a toggle in the settings of the reader, the css work is all there and it will work very well to allow a few different schemes (or just 1 dark one if you want to make it easier).

**Comment by gelsas** [comment]
Is the latest version already live in calibre web? 
Because it seems to be breaking for me.

![isssuuuueee](https://user-images.githubusercontent.com/282734/50914927-fc4a5f00-1437-11e9-90b4-215970dfc094.PNG)

**Comment by OzzieIsaacs** [comment]
Yes, the lastest version is merged, I can confirm, I see the same, @leram84, @hexeth could you please take a look at it (long book titles on widescreen monitors seem to overlap each other)

**Comment by gelsas** [comment]
> * Settings are quite difficult to read
>   ![imagen](https://user-images.githubusercontent.com/2266612/47963439-cb5f3f80-e02c-11e8-992f-6d352cac8bd7.png)

I also noticed that the settings at least for me are still very difficult to read.

**Comment by leram84** [comment]
yes @OzzieIsaacs the overlapping titles, the new publishers page headers, and a couple other small bugs are fixed in the new css update i will push when I've finished testing everything thoroughly (thats the last css update i was talking about). 

@gelsas I believe you are running the older version of cw. If you upgrade you should see that resolved

**Comment by gelsas** [comment]
@leram84 I am using this version:

08.01.19, 20:58 | Latest Version

So it is the version from yesterday, any idea why I still have the issue (i cleared the cache etc. already)

**Comment by leram84** [comment]
the pr is up https://github.com/janeczku/calibre-web/pull/758

but hang on @gelsas are you still using the nginx subfilter to install the theme? thats the only thing that would make sense (you using an outdated version through the subfilter), cause the built in theme is fully updated (from user settings > Theme > caliBlur! Dark Theme (Beta) )

**Comment by gelsas** [comment]
@leram84 I just installed a new instance of calibre web via this docker image (to test the new caliblur) https://hub.docker.com/r/technosoft2000/calibre-web/ (the latest version).

Or do I need to do it differently ?

**Comment by Technosoft2000** [comment]
@gelsas
I'll do some tests with my docker container today at afternoon to see if I get the same issue which you've described and give feedback. 

Do you directly access the Calibre-Web instance from the browser or is a reverse proxy in between?

**Comment by adocampo** [comment]
You guys ROCK! I'm very happy with the progress both in the theme as in the easiness to set up through docker container \o/  You deserve a HUGE thanks!  (f**k off, google books! :smiling_imp: )

Same here with just updated technosoft's docker image
![imagen](https://user-images.githubusercontent.com/2266612/50956685-948a2780-14bc-11e9-97f4-767d0f42517f.png)

Besides this, I would like to set this globally both for all my existing users and the new ones, and on the login form **without using nginx**, just the docker, is that possible?

A black reader will be AWESOME indeed! :D

Finally, on the tasks screen, shouldn't be the lines of the table shown in black instead of white? (lines on user settings are black, just like they are in plex.
![imagen](https://user-images.githubusercontent.com/2266612/50957013-74a73380-14bd-11e9-8513-ad413843acc2.png)

**Comment by gelsas** [comment]
> I would like to set this globally both for all my existing users and the new ones, and on the login form **without using nginx**, just the docker, is that possible?

I would like to do that too.

Furthermore I noticed one small thing which maybe could be added. On the Book Detail page when I hover over the cover I was expecting a "Read" or/and a "Download" Button because on Plex it is the same with tv shows etc.

Here an example of how I thought it would work. (right now the read download buttons are "hidden" at the far right and I would love to have it like something in my screenshot)

![unbenannt](https://user-images.githubusercontent.com/282734/50976101-6ffb7300-14ef-11e9-8c89-a92fc821df7e.PNG)

**Comment by gelsas** [comment]
I noticed one more thing. When I download a file via the download button then I am redirected to a blank page. Shouldn't it still show the book page ?

![123](https://user-images.githubusercontent.com/282734/50977479-a8508080-14f2-11e9-9181-ec33fcb828c4.PNG)

**Comment by leram84** [comment]
ok, there is definitely some versioning issues here, so i dont want to get to deep into troubleshooting all these issues until after ozzie moves the toggle server side. That will be a clear indicator of which version caliblur a user is using. @adocampo you, for example, are definitely on an older version (that is a very old task page). I'm sure you will see a bunch of differences with your version and this https://raw.githubusercontent.com/leram84/layer.Cake/Screenshots/caliBlurP1.PNG (especially the top bar) @gelsas im not as certain about cause your book details page has some pretty recent adjustments, but i cant be sure of the timeline lol. lmk if your top bar matches that ss as well. In any case, there might be some issues with that docker. I'll take a look after the settings move.

@gelsas the hover over cover thing was actually a point of contention for me lol. I would have loved to do it, but nothing really makes sense... do we do it as a download button? what if they have multiple files to dl. do we do it as a read-in-browser button? what if the user doesn't do epub, or doesn't have an epub for that book... or has epub AND pdf or something.... there just isn't a clean translation between plex's "Play" and cw's "read/download".

**Comment by gelsas** [comment]
Version | Details
1/10/19, 8:25 AM | Current version

And the settings and task page look the same as @adocampo screenshots. And I am on the latest version (where your latest pull request is already included)

@leram84  Maybe I have a suggestion for that.

Like it Plex when there are different versions we display the number in the top right corner of the cover.
And we add an extra dropdown (which equals the Sound selection in plex).

Then we display a read and a download button (in addtion(?) to those on the far right) and then it will open or download the file format selected in the dropdown.

Just an idea. What do you think?

Here is a quick  mockup of what I mean. (i didn't edit the screenshot perfectly but I think you get the idea)
![unbenannt](https://user-images.githubusercontent.com/282734/50981794-09308680-14fc-11e9-823a-fda10e53a2ce.PNG)

**Comment by leram84** [comment]
I dont love that, since 1) you'd have to specify the format first and then click the poster (not very intuitive) and 2) Choosing to make it readinbrowser to begin w is problematic since many users dont actually have epubs at all (or have them randomly on some books), so then you have a ui element that feels like the default (or most important) button, but that SOMETIMES exists and sometimes doesnt... As much as i want to keep this in line w plex (and believe me its definitely something iv thought a LOT about) it just doesn't feel right here.

That being said, even if i wanted to do this the way u describe, its just not really even practical for a theme like this. I dont have access to source, so i have to write everything on top of the existing code. The most challenging part of all this was to position elements in a way that would work for every combination of possible configs. Just getting everything to line up in the top right and then collapse right when someone has a "send to kindle" button enabled or not, or epub or not, etc took literal months of hacking lol.

**Comment by adocampo** [comment]
>  @adocampo you, for example, are definitely on an older version (that is a very old task page). I'm sure you will see a bunch of differences with your version and this https://raw.githubusercontent.com/leram84/layer.Cake/Screenshots/caliBlurP1.PNG (especially the top bar)

I created the image just this morning. I see the main page just like you... 
![imagen](https://user-images.githubusercontent.com/2266612/50987321-a7771900-1509-11e9-898d-3d89bf4800a4.png)

Let me re-create the docker, but I doubt something changed since this morning.

**Comment by Technosoft2000** [comment]
I've update my instance to latest Calibre-Web version **1/10/19, 6:26 PM** and I can confirm the color issue at **Basic Configuration** site.

To check if the CSS is the actual one I've saved the one from Calibre-Web via the browser (Chrome 71.0.3578.98) and downloaded the actual one from github ->https://github.com/janeczku/calibre-web/tree/master/cps/static/css

Then I've checked them with WinMerge if they are the same and they are 100% identical.
Here they are attached with the extension txt because github doesn't allow directly to attach css files.

[github-caliBlur.min.css.txt](https://github.com/janeczku/calibre-web/files/2746731/github-caliBlur.min.css.txt)

[browser-caliBlur.min.css.txt](https://github.com/janeczku/calibre-web/files/2746730/browser-caliBlur.min.css.txt)

So the Docker instance contains the latest version which is available.

In addition I've tested this issue in different Browsers: Chrome, Safari, Edge
and in all I had this issue.

Also after a Hard Reload in Chrome the issue is still there, so it can't be a browser cache problem.
And I've also tested to use the Calibre-Web site directly without the Synology Reverse Proxy and get the color issue at the **Basic Configuration** site.

**Comment by hexeth** [comment]
Does your console contain any errors? I am also running your docker on its latest version and am not having the same issue. 

Is this happening upon initial setup, or following setup?

**Comment by adocampo** [comment]
Just docker? No reverse proxy inbetween?

**Comment by hexeth** [comment]
You're right - the issue appears only when using an internal address. It works fine via RP, but not internally

**Comment by Technosoft2000** [comment]
No errors at the Chrome Console

**Comment by Technosoft2000** [comment]
> You're right - the issue appears only when using an internal address. It works fine via RP, but not internally

Only to clarify - it works when caliBlur! is used via Reverse Proxy configuration then it works like it is intended, and with direct usage in Calibre-Web (like it is via internal access) it doesn't.

Please correct me if I'm wrong

**Comment by Technosoft2000** [comment]
Oh that is great @hexeth - by the way thanks for this awesome theme 👍

**Comment by leram84** [comment]
Aight peoples its DONE!!! like really done! The theme has been fully and successfully merged into cw proper, the toggle is now in admin settings in the ui tab and enabled for all users (THANK YOU @OzzieIsaacs ), And all bug fixes and language support is included. We are now fully in sync w cw and will only be making changes to the theme as cw adds features. Can't believe we finally made it. Massive massive massive props to @hexeth I can't really imagine what this would have turned into without him.

As soon as this is merged, you can all clear out any nginx subfilters you were using (if you were) and just run the theme natively https://github.com/janeczku/calibre-web/pull/765

This is a good day :)

**Comment by Technosoft2000** [comment]
@leram84 
Many thanks for this theme, great job :)

**Comment by adocampo** [comment]
I'm completely impressed by your work, guys! Very very good job! :smile: 
Indeed, I can set up globally this awesome theme and now settings and tasks table draws as expected, even logon screen match the theme :D

I noticed, but a pair of things that it seems doesn't match the theme. The first one is the "Send to kindle" button, that shows the icon and text with a grey background, and it seems a bit out of place with the rest of the buttons (I deleted the cache and tried several browsers and private navigations)
![image](https://user-images.githubusercontent.com/2266612/51077105-f6f04d00-16a1-11e9-968d-22f9461d5cd5.png)

The other is the loading spining when updating calibre web. I think the orange spinning animation shown on plex would be the perfect match (just like the one when loading book covers)
![image](https://user-images.githubusercontent.com/2266612/51077162-bc3ae480-16a2-11e9-9e78-a834c18ebcbf.png)

In other order of things, I still vote for a dark reader, it would be the perfect match for CaliBlur! theme, imho.

Again, awesome work and thank you very much guys, you're incredible ;)

**Comment by rg9400** [comment]
When you are in anonymous browsing mode, you have to click on the profile and then guest to get to the login screen. Both this and registration are somewhat hidden and not very intuitive. Especially since it does not say login anywhere. 

Also, maybe it's just me, but the guest button doesn't work. I have to right click and go to the link separately. 

Thanks for all the continued help and support

**Comment by hexeth** [comment]
@adocampo the issue with the Send to Kindle button should be fixed with the latest PR.

**Comment by adocampo** [comment]
@hexeth now the icon is here but the functionality has been lost: when clicking the icon to "Send to Kindle", it disappears, the message "Book successfully queued for sending to username@kindle.com" doesn't appear and I don't see the tasks of converting and sending to kindle.
![image](https://user-images.githubusercontent.com/2266612/51259936-72f1da00-19ad-11e9-9e55-7e10c5dbc3c3.png)
Sending a test email from SMTP Settings confirms I have SMTP well configured and I can see the task on the test email, so I changed to standard CW theme and I try it again.

First of all, clicking on "Send to Kindle" shows a dropdown where it let me choose the format before converting
![image](https://user-images.githubusercontent.com/2266612/51260362-691ca680-19ae-11e9-9779-3bb6fc2efcdc.png)
while on CaliBlur! doesn't appear
![image](https://user-images.githubusercontent.com/2266612/51260441-936e6400-19ae-11e9-8c97-e54fbaaeda5a.png)

PS: I'm using calibre-convert, not kindlegen, if that matters.

**Comment by OzzieIsaacs** [comment]
I think I know whats going wrong, let me take a look

**Comment by OzzieIsaacs** [comment]
Okay I checked it, my idea was wrong, the issue is related to the caliblur theme.

**Comment by leram84** [comment]
yes, i dont think this option existed (or we just didn't know about it) when i was building the theme. I've only ever seen a single "send to kindle" button, never a drop down. We will need to rework the button to behave like the other drop down menus. (that also makes sense why people were coming up w a `#sendbtn2` ID that was breaking css. We'll need to roll back that pr @hexeth and then i can redo the css here. 

Are there any extra steps to getting the option to convert while sending? Or is this default behavior now?

**Comment by OzzieIsaacs** [comment]
If you only have one file to send/convert you See the old Button. If there is more than one option ( like send pdf or convert EPUB to mobi and send) you see the new button.
To get the convert option you need to have smtp server setup, user has to have an valid entry in kindle-email and in admin section external binaries, a binary has to be entered, and kindlegen converter or calibre‘s converter has to be choosen

**Comment by hexeth** [comment]
@OzzieIsaacs Leram jumped the gun when he said to revert the `sendbtn` PR. The issue is that the caliBlur.js did not assign a class to the unordered list for send-to-kindle, which it does for the other drop-downs. The oversight was entirely because I wasn't aware it could be a dropdown, and my JS overrides all bootstrap toggles, there was no toggle event for the dropdown.

I have submitted a PR of the JS. In addition to this code @leram84 may need to do some CSS for the class 'sendtokindle-drop'. `sendbtn2` should also be changed back to `sendbtn` again.

**Comment by adocampo** [comment]
By the way, now JS  and... \*cough\*...CSS need to be modified you could  \*cough\* take a look to  \*cough\*darkreadertheme\*cough\* :innocent:

**Comment by leram84** [comment]
not sure if you're talking to me or ozzie but just to be clear, caliblur won't "dark-mode" the reader. I can't give user options in a theme and it doesn't make sense to go dark if that is the only view available. It would only make sense to do the dark reader if it is an option in the reader settings. And that would be a useful tool for non caliblur users as well anyway. 

So i can do the css for it, but ozzie would have to figure a way to make a toggle for it in the reader.

**Comment by adocampo** [comment]
Well, I trhrew the idea to the air. I think the best would be a setting on the reader itself under its settings
![imagen](https://user-images.githubusercontent.com/2266612/51439648-907cb780-1cbd-11e9-8c7f-762c996fb7ae.png)
I think calibre-web is using [futurepress' epub.js](https://github.com/futurepress/epub.js/), perhaps we can PR there or modify the code on CW. Anyway, caliBlur! should use dark reader by default, or CW should let choose the reader theme by default.

**Comment by OzzieIsaacs** [comment]
I created an issue for the dark epub reader theme (#778). We should discuss this there.

**Comment by adocampo** [comment]
ok @OzzieIsaacs let's speak there. 

On the other hand, I confirm "Send to Kindle" button's functionality is working as expected now, and it looks and feel like the other buttons :)

**Comment by gelsas** [comment]
> The other is the loading spining when updating calibre web. I think the orange spinning animation shown on plex would be the perfect match (just like the one when loading book covers)
> ![image](https://user-images.githubusercontent.com/2266612/51077162-bc3ae480-16a2-11e9-9e78-a834c18ebcbf.png)

The only thing I have noticed which could be changed is the loading icon as adocampo mentioned before. 

With a dark reader the caliblur theme would be completely perfect. But I am already so so happy with it. Especially at night the dark colors are easy on the eyes.

**Comment by adx442** [comment]
Is there any way to have this theme affect the books being read in the web viewer?  Mine just go to stark white backgrounds.  The UI is lovely, but I was hoping this theme would be used for the actual books themselves as well as the navigation and management.

**Comment by itsmehemant123** [comment]
@adx442 that's being discussed here #778

**Comment by OzzieIsaacs** [comment]
@hexeth, @leram84 meanwhile I replaced the upload spinner with a progress bar, so there is no need to change the color of the spinner

**Comment by hobsawn** [comment]
I love your work, a really think that the inspiration (plex) add good aesthetic to your project. There one thing for change (i dont know if is possivel now) how to keep the proportion of book covers

![image](https://user-images.githubusercontent.com/56079489/183132970-a51a9cd8-3943-4d92-998f-1af4e051b5cc.png)
this is a print of calibre portable 

![image](https://user-images.githubusercontent.com/56079489/183133051-9289b5d9-1c5f-418b-a267-df295e260481.png)
this is a print of calibre web with caliBlur

:)
