### ISSUE TITLE
Google drive config problem: client_secret.json is missing or not readable

### ISSUE THREAD

**Issue by mariusst** [janeczku/calibre-web#520]
I installed calibre-web and try to setup gdrive but when accessing calibre-web for the first time it wouldn't let me use gdrive throwing this error "Google drive config problem: client_secret.json is missing or not readable"; Although I have client_secret.json in calibre-web/cps owned by the same user.

**Comment by OzzieIsaacs** [comment]
The file is supposed to be in calibre-web folder and not in the cps folder

**Comment by OzzieIsaacs** [comment]
Sorry, I corrected readme. I don‘t know how anybody got it every to run with the old instructions

**Comment by mariusst** [comment]
Sorry, it doesn't work even after I moved the file in calibre-web dir. I also tried renaming the file as "client_secrets.json" like in the Readme, still throws the same error...

**Comment by OzzieIsaacs** [comment]
Okay, fixed the wrong name in the readme. Are you using windows or Linux? Which python version are you using? How do you start calibre-web (do you change into directory, or are you calling Calibre-web with the complete pathname)?
Final try would be replacing client_secret.json in lines 1553, 2522, 2525 with the complete path to the file. If this is not helping you have a accessrights problem

**Comment by OzzieIsaacs** [comment]
If you download the file from the google developer console the name should something like: blblblablabla_client_secret(s).json. Is this secret.json, or secrets.json. I case of secrets.json please change the name in the above mentioned lines to ...secrets.json and try again

**Comment by OzzieIsaacs** [comment]
Yes I agree with you, there is naming problem

**Comment by mariusst** [comment]
The file from google developer console is client_secret.json not client_secrets.json

**Comment by mariusst** [comment]
Hey, Thanks, finally works.... almost.
It was not easy. I encountered a few problems:

1. When activating the Authenticate Google Drive button there's no actually page redirection, if I remember correctly, you have to also click submit. Anyway it took some retries until I got to the google page.
2. I'm not sure if the files settings.yaml and a gdrivecredentials are created after you hit Authenticate Google Drive button. Only after I created manually settings.yaml I managed to access the google page for permision.
3. Starting the systemd service doesn't work with the example from the readme it throws the initial error (client_secret.json is missing or not readable). I Manged to make it work by adding this line in the cps.service file "WorkingDirectory=/var/www/calibre-web/". So maybe this line should be added in the cps.service example from the readme. 

Another problem that I encountered is that epub player doesen't work (although the pdf player works). It throws this error in the calibre-web.log:

> [2018-06-07 18:57:58,948] {/var/www/calibre-web/vendor/flask/app.py:1761} ERROR - Exception on /read/374/epub [GET]
Traceback (most recent call last):
  File "/var/www/calibre-web/vendor/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/www/calibre-web/vendor/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/www/calibre-web/vendor/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/calibre-web/vendor/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/www/calibre-web/vendor/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/calibre-web/cps/web.py", line 393, in decorated_view
    return login_required(func)(*args, **kwargs)
  File "/var/www/calibre-web/vendor/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/var/www/calibre-web/cps/web.py", line 1934, in read_book
    raise ValueError('Error opening eBook. File does not exist: ', epub_file)
ValueError: ('Error opening eBook. File does not exist: ', u'/var/www/calibre-web/tmp/Quentin Meillassoux/After Finitude (374)/After Finitude - Quentin Meillassoux.epub')
 
It seems that it searches the epub file in the local temporary folder (where metadate.db is) and not in gdrive.

**Comment by OzzieIsaacs** [comment]
Perfect. I will solve the file not found problem in the code ( I didn‘t test this usecase). Regarding the nonworking epubbrowser, I already know this (#502) I’m trying to fix it soon.
The settings.yaml is created after you press submit after ticking enable google drive. The gdrivecredential is created after you press authenticate and google has verified that you are allowed to access. May I ask which browser you are using? On Firefox it looked more straight forward to me.

The setuproutine isn‘t 100% perfect, but much better and easier to handle (if it works, of course) compared to the routine before.

**Comment by mariusst** [comment]
At first I used Firefox but I also tried on Chromium. In Chromium I managed to get to the google permission page, so to me Chromium was more straight forward.
Anyway, Thanks again! Keep up the good work

**Comment by saitoh183** [comment]
So i just updated and moved my client_secrets.json file from the cps folder. Now i saw that it was looking for client_secret.json so i renamed it. When i click on Authenticate button, i got a internal error. I checked the logs and i see this

`InvalidConfigError: Invalid client secrets file ('Error opening file', 'client_secrets.json', 'No such file or directory', 2)`

it is looking for client_secrets.json again.

Im using the docker image btw.

**Comment by saitoh183** [comment]
humm...it just stop working now...

`
[2018-06-14 14:10:50,557] ERROR in gdriveutils: GDrive gdrive_credentials file not present, reauthenticate in config section`

**Comment by OzzieIsaacs** [comment]
The filenaming problem shouldbe fixed now, and also accessing settings.yaml and gdrive_credentials should now work from outside of cps root folder.
