### ISSUE TITLE
After update Nothing is working with Gdrive anymore

### ISSUE THREAD

**Issue by saitoh183** [janeczku/calibre-web#525]
So after reading the other Gdrive post, i updated my docker image via the update button on the calibre-web  admin page. After that everything broke.

- I was able to re-authenticate googledrive (https://github.com/janeczku/calibre-web/issues/520#issuecomment-397334601)

- Can't download anything

```
[2018-06-14 14:58:46,854] {/usr/lib/python2.7/site-packages/flask/app.py:1560} ERROR - Exception on /download/456/mp3/456.mp3 [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/calibre-web/app/cps/web.py", line 393, in decorated_view
    return login_required(func)(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/calibre-web/app/cps/web.py", line 496, in inner
    return f(*args, **kwargs)
  File "/calibre-web/app/cps/web.py", line 2002, in get_download_link_ext
    return get_download_link(book_id, book_format)
  File "/calibre-web/app/cps/web.py", line 393, in decorated_view
    return login_required(func)(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/calibre-web/app/cps/web.py", line 496, in inner
    return f(*args, **kwargs)
  File "/calibre-web/app/cps/web.py", line 1988, in get_download_link
    df = gdriveutils.getFileFromEbooksFolder(Gdrive.Instance().drive, book.path, '%s.%s' % (data.name, book_format))
  File "/calibre-web/app/cps/gdriveutils.py", line 173, in getFileFromEbooksFolder
    drive = getDrive(drive)
  File "/calibre-web/app/cps/gdriveutils.py", line 92, in getDrive
    drive.auth.Refresh()
  File "/usr/lib/python2.7/site-packages/pydrive/auth.py", line 468, in Refresh
    raise RefreshError('No credential to refresh.')
RefreshError: No credential to refresh.
```
- Covers arent downloading..

`[2018-06-14 15:03:20,152] {/calibre-web/app/cps/web.py:1816} ERROR - J. D. Robb/Echoes in Death [Audiobook] (456)/cover.jpg not found on GDrive`

**Comment by saitoh183** [comment]
So i restarted from scratch the entire process. It seemed to work for a bit and then it died. When i click on the configure button to access the google drive settings, i get a 505

```
::ffff:172.18.0.11 - - [2018-06-14 18:51:05] "GET /calibreweb/ HTTP/1.0" 200 80118 0.278708,
Your browser has been opened to visit:,
[2018-06-14 18:51:16,699] ERROR in gdriveutils: GDrive gdrive_credentials file not present, reauthenticate in config section,
::ffff:172.18.0.11 - - [2018-06-14 18:51:14] "GET /calibreweb/static/css/style.css?q=30af816 HTTP/1.0" 200 5371 0.004675,
::ffff:172.18.0.11 - - [2018-06-14 18:51:14] "GET /calibreweb/static/css/libs/bootstrap.min.css?q=ec3bb52 HTTP/1.0" 200 324 0.005630,
::ffff:172.18.0.11 - - [2018-06-14 18:51:13] "GET /calibreweb/admin/view HTTP/1.0" 200 13548 0.085915,
::ffff:172.18.0.11 - - [2018-06-14 18:51:05] "GET /calibreweb/static/css/fonts/glyphicons-halflings-regular.woff2 HTTP/1.0" 200 324 0.003602,
::ffff:172.18.0.11 - - [2018-06-14 18:51:05] "GET /calibreweb/static/css/fonts/GrandHotel-Regular.ttf HTTP/1.0" 200 324 0.005009,
::ffff:172.18.0.11 - - [2018-06-14 18:51:05] "GET /calibreweb/cover/Maxime%20Chattam/L%27alliance%20des%20trois%20%5BAudiobook%5D%20%28166%29 HTTP/1.0" 200 182886 0.007710,
[2018-06-14 18:51:05,639] ERROR in web: Maxime Chattam/L'alliance des trois [Audiobook] (166)/cover.jpg not found on GDrive,
::ffff:172.18.0.11 - - [2018-06-14 18:51:05] "GET /calibreweb/cover/Patricia%20Cornwell/Sans%20raison%20%28396%29 HTTP/1.0" 200 182886 0.008108,
[2018-06-14 18:51:05,631] ERROR in web: Patricia Cornwell/Sans raison (396)/cover.jpg not found on GDrive,
::ffff:172.18.0.11 - - [2018-06-14 18:51:05] "GET /calibreweb/cover/James%20Patterson/Season%20of%20the%20Machete%20%28512%29 HTTP/1.0" 200 182886 0.009838,
[2018-06-14 18:51:05,621] ERROR in web: James Patterson/Season of the Machete (512)/cover.jpg not found on GDrive,
::ffff:172.18.0.11 - - [2018-06-14 18:51:05] "GET /calibreweb/cover/J.%20D.%20Robb/Glory%20in%20Death%20%5BAudiobook%5D%20%287%29 HTTP/1.0" 200 182886 0.018302,
[2018-06-14 18:51:05,579] ERROR in web: J. D. Robb/Glory in Death [Audiobook] (7)/cover.jpg not found on GDrive,
[2018-06-14 18:51:05,578] ERROR in gdriveutils: GDrive gdrive_credentials file not present, reauthenticate in config section
```
gdrive_credentials is there and if i delete it and redo the authentication process, it will work again for awhile and fall back to the error above.

**Comment by OzzieIsaacs** [comment]
I fixed the problem from #520 and found some additional problems related to start dir diffrent from calibre-web root dir. Could you please try again with the newest commit?

**Comment by saitoh183** [comment]
alright will do when i get a few minutes

**Comment by saitoh183** [comment]
@OzzieIsaacs 

still no go...when i hit the button to monitor metatdata.db, i get internal error.
```
[2018-07-14 01:29:39,231] {/usr/lib/python2.7/site-packages/flask/app.py:1560} ERROR - Exception on /gdrive/watch/subscribe [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/calibre-web/app/cps/web.py", line 468, in inner
    return f(*args, **kwargs)
  File "/calibre-web/app/cps/web.py", line 1564, in watch_gdrive
    'web_hook', address, gdrive_watch_callback_token, current_milli_time() + 604800*1000)
  File "/calibre-web/app/cps/gdriveutils.py", line 266, in watchChange
    drive = getDrive(drive)
  File "/calibre-web/app/cps/gdriveutils.py", line 92, in getDrive
    drive.auth.Refresh()
  File "/usr/lib/python2.7/site-packages/pydrive/auth.py", line 468, in Refresh
    raise RefreshError('No credential to refresh.')
RefreshError: No credential to refresh.
```

also i see `
[2018-07-14 01:31:59,057] ERROR in web: Sue Grafton/_C_ Is for Corpse (Kinsey Millhone (244)/cover.jpg not found on GDrive` and the cover.jpg is there

**Comment by OzzieIsaacs** [comment]
Meanwhile I could reproduce the error and I'm working on a fix.

**Comment by saitoh183** [comment]
right now im using the Unionfs to get around the problem

**Comment by OzzieIsaacs** [comment]
The fix is included in one of the latest commits, it hopefully should work now
