### ISSUE TITLE
Download button with Caliblur error

### ISSUE THREAD

**Issue by stephsabb** [janeczku/calibre-web#818]
Hello,
Download button does not work with latest of Caliblur theme :( 
Work with default theme
Thanks

**Comment by OzzieIsaacs** [comment]
Update of bootstrap lib causes problem

**Comment by OzzieIsaacs** [comment]
Update to newest commit should solve the problem

**Comment by hexeth** [comment]
Caliblur theme issues are related to the loader changes. I have this fixed in my internal build. The Read-More for book descriptions has also somehow become broken, so I am waiting on @leram84 to fix that issue before doing a PR on those changes.

**Comment by OzzieIsaacs** [comment]
I'm reverted the master branch to bootstrap 3.3.7, it should now work there (sorry, didn't expect this impact). Version 3.4.0 is now only used on development branch.

**Comment by hexeth** [comment]
3.3.7 did not seem to resolve the issue for me, but we have it sorted on my dev branch

![image](https://user-images.githubusercontent.com/7627137/53114907-c3eb7580-34f9-11e9-8e0e-1f564744322a.png)

**Comment by leram84** [comment]
yeah, the css is kind of a house of cards at this point. The loader div was a very useful thing to hijack to add all the additional content we needed (blur bg's, drop down menus, etc) because it was present in every page but we didn't actually need it's content lol. Hex has a fix for this in our dev branch. It's not pretty, but its definitely the best way to handle it on caliblur's end cause there are just too many hooks into that wrapper, so he is just inserting the whole thing back in the js:

```
// Re-add loader to fix CSS/Jquery targets 
$( '<div id="loader" hidden="true"><center><h3>Uploading...</h3><span>please don\'t refresh the page</span>".                      "<br><img src=""></center></div>'  ).insertAfter( '.navbar.navbar-default.navbar-static-top ' );
```
It's up to you if you want to leave the loader in as you've reverted it now, and just not call it in stock cw, or go back to removing it and have caliblur.js reinsert it. The former would probably be better for caliblur, but im not sure why you removed it to begin with so.... :)

**Comment by OzzieIsaacs** [comment]
I removed it, because I merged a progress bar for uploading files, so there was no need for the text anymore.
![grafik](https://user-images.githubusercontent.com/6438895/53117049-50258900-354a-11e9-8517-24c323d6f8dd.png)
I's now inserted on 'layout.html', if the caliblur! theme is active
