### ISSUE TITLE
error 500 on adding many books

### ISSUE THREAD

**Issue by Oreolek** [janeczku/calibre-web#890]
1. download this torrent: https://archive.org/details/BeneathCeaselessSkies
2. try to add books - it will upload them all but fail with error 500 during the import

```
Traceback (most recent call last):
  File "calibre-web/vendor/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "calibre-web/vendor/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "calibre-web/vendor/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "calibre-web/vendor/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "calibre-web/vendor/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "calibre-web/cps/web.py", line 348, in decorated_view
    return func(*args, **kwargs)
  File "calibre-web/cps/web.py", line 490, in inner
    return f(*args, **kwargs)
  File "calibre-web/cps/web.py", line 3868, in upload
    "<a href=\"" + url_for('show_book', book_id=book.id) + "\">" + uploadText + "</a>")
  File "calibre-web/cps/worker.py", line 406, in add_upload
    self.UIqueue[self.current]['formStarttime'] = self.queue[self.current]['starttime']
IndexError: list index out of range
```

**Comment by OzzieIsaacs** [comment]
For me it's working. 
But looks like a timing problem, I have to think on it.

**Comment by OzzieIsaacs** [comment]
Are you using docker? 
Which python version are you using?
Do you have Imagemagick installed? (-> about section)

**Comment by Oreolek** [comment]
Not using docker, Python 2.7.12, Ubuntu 16.04 LTS, ImageMagick 6.8.9-9

**Comment by FrouxBY** [comment]
Hi there,

**Comment by erauzkin** [comment]
I have the same problem, with LinuxServer (Docker) version.

**Comment by OzzieIsaacs** [comment]
I think I see the problem. Line 206 in worker has also protected by a lock. I'll try to fix it this evening

**Comment by OzzieIsaacs** [comment]
90% chance that it is fixed with the newest commit. (For those who are using docker and facing this issue, you have to wait until the docker container is rebuild)

**Comment by floviolleau** [comment]
Hi,

I installed calibre at the commit 5f228fb and I still have issues when I multiple upload.

I don't have any errors in logs but on UI, I have a 502 proxy error:
![image](https://user-images.githubusercontent.com/5442973/62080713-7fef6000-b251-11e9-81b9-123673037154.png)

Do you have an idea?

Thanks for your help here.

**Comment by OzzieIsaacs** [comment]
This is a different error message than before, did you had the intial problem before? Otherwise I would create a new issue for this one.
Are the books added afterwards?
Do you use docker? reverse proxy? which one?

**Comment by floviolleau** [comment]
I think I had this issue before that commit but I cannot be 100% sure.

Books are correctly added afterwards. I can see it in tasks page and if I do a md5sum check, all is OK.
I don't use Docker (I'm on a Rpi 3). I configured an Apache to do a reverse proxy to the calibre's port.

**Comment by zelazna** [comment]
Hello, i have the same issue with a AWS EC2 instance behind a load balancer

**Comment by p-rintz** [comment]
Same issue here, using latest released version inside a docker container:

Error:

```
[2019-10-06 10:13:48,657] ERROR in app: Exception on /upload [POST],
Traceback (most recent call last):,
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2446, in wsgi_app,
    response = self.full_dispatch_request(),
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1951, in full_dispatch_request,
    rv = self.handle_user_exception(e),
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in handle_user_exception,
    reraise(exc_type, exc_value, tb),
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1949, in full_dispatch_request,
    rv = self.dispatch_request(),
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1935, in dispatch_request,
    return self.view_functions[rule.endpoint](**req.view_args),
  File "/app/calibre-web/cps/web.py", line 349, in decorated_view,
    return login_required(func)(*args, **kwargs),
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 261, in decorated_view,
    return func(*args, **kwargs),
  File "/app/calibre-web/cps/web.py", line 495, in inner,
    return f(*args, **kwargs),
  File "/app/calibre-web/cps/web.py", line 3894, in upload,
    "<a href=\"" + url_for('show_book', book_id=book.id) + "\">" + uploadText + "</a>"),
  File "/app/calibre-web/cps/worker.py", line 414, in add_upload,
    self.UIqueue[self.current]['formStarttime'] = self.queue[self.current]['starttime'],
IndexError: list index out of range
```

**Comment by aschi2403** [comment]
I also have the same Issue, at the beginning the upload worked, but now it doesn't, I now have a large Book Collection (added with the Calibre Desktop Program), whenever I try uploading a book (even a single one) over calibre-web I get a 500 error and then the application shows an internal server error whenever loading it.
I'm using Docker, a restart of the container helps.

**Comment by OzzieIsaacs** [comment]
I found the problem. If the task list gets bigger than 20 entries during the upload, the completed tasks should get deleted, and this causes the problem.
