### ISSUE TITLE
I do not see read books in the Read Books menu in Calibre-Web

### ISSUE THREAD

**Issue by dzialeczko** [janeczku/calibre-web#971]
I do not see read books in the Read Books menu in Calibre-Web.

I used the Wiki information: https://github.com/janeczku/calibre-web/wiki/Configuration "UI Configuration" and Issues: https://github.com/janeczku/calibre-web/issues/409; https://github.com/janeczku/calibre-web/issues/704.

I set "Link read / unread status to Caliber column".

There is a READ / UNREAD synchronization between the Caliber base and Caliber-Web, OK. Unfortunately, in the Read Books menu (left menu on Caliber-Web) I do not see any read books. I have 50 books and all of them are in Unread Books (should be 40 Unread and 10 Read).
I only use one Caliber account.

My data:
OS: Windows 10
Calibre-Web: 0.6.5 Beta
Calibre: 3.46
![calibre-web](https://user-images.githubusercontent.com/53253501/61775805-ead80b80-adf9-11e9-99eb-397d8ac5f38e.PNG)

**Comment by dzialeczko** [comment]
I forgot to write that it works correctly in version 0.6.2. :)
It does not work in the version 0.6.5 Beta.

**Comment by OzzieIsaacs** [comment]
It's fixed now. We did a lot of changes to the code and test coverage has some holes in it.

**Comment by drneal12** [comment]
This is still happening to me on 0.6.5 Beta with current master branch downloaded yesterday.

**Comment by drneal12** [comment]
@OzzieIsaacs Is there a way to download this changes?  I'm on 0.6.5 Beta and this bug is still present.

**Comment by OzzieIsaacs** [comment]
If you switch to nightly updates and download the newest commit, it should work. If not, you are having another problem and I need more information (logbooks, error message, exact describtion of behavior, your environment...)
